name: 'AWS ECS Upsert Service Action'
description: 'Updates ECS service with new task definition, creates service if it does not exist'
inputs:
  cluster_name:
    description: 'Name of ECS cluster'
    required: true
  service_name:
    description: 'Name of ECS service'
    required: true
  task_definition:
    description: 'Path to task definition file'
    required: true
  load_balancers:
    description: ''
    required: false
  service_registries:
    description: ''
    required: false
  service_tags:
    description: 'Comma separated key=value pairs of tags to apply to service'
    required: false
    default: ''
  desired_count:
    description: 'Number of tasks to run'
    required: false
    default: "1"
  enable_execute_command:
    description: 'Enable ECS execute command'
    required: false
    default: "false"
  launch_type:
    description: 'Launch type for service'
    required: false
    default: EC2
  subnets:
    description: 'Comma separated list of subnet ids'
    required: false
    default: ''
  security_groups:
    description: 'Comma separated list of security group ids'
    required: false
    default: ''
  deployment_circuit_breaker_enable:
    description: 'Enable deployment circuit breaker'
    required: false
    default: "true"
  deployment_circuit_breaker_rollback:
    description: 'Enable deployment circuit breaker rollback'
    required: false
    default: "true"
  assign_public_ip:
    description: 'Assign public IP to tasks'
    required: false
    default: "false"
runs:
  using: 'node20'
  main: 'dist/index.js'